# Comparison of weights in JTI, UTMOST, and PrediXCan

## Summary of weight vector statistics by gene and weights across all genes and methods
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(patchwork)
library(GGally)

load_weights <- function(method, tissue) {
  db <- fs::path("..", "data", "weights", paste0(method, "_", tissue, ".db"))
  conn <- DBI::dbConnect(RSQLite::SQLite(), db)
  df <- tbl(conn, "weights") %>% collect()
  DBI::dbDisconnect(conn)
  df %>% mutate(method = method)
}

load_tissue <- function(tissue, methods = c("UTMOST", "PredixCan", "JTI")) {
  methods %>%
    map(function(m) load_weights(m, tissue)) %>%
    bind_rows()
}

summarize_weights <- function(tissue_df) {
  tissue_df %>%
    group_by(gene, method) %>%
    summarise(
      l1_norm = abs(sum(weight)),
      l2_norm = sqrt(sum(weight^2)),
      non_zero = n(),
      .groups = "drop"
    )
}

plot_tissue_summary <- function(tissue) {
  title <- paste("Distribution of L1 norm, L2 norm, and sparcity of gene weights for", tissue)
  weights <- load_tissue(tissue)
  summary <- weights %>% summarize_weights()

  color_s <- scale_color_manual(values = c("#B4D88B", "#A6CEE2", "#FCAE6B"))
  base <- ggplot(summary, aes(color = method)) +
    color_s +
    guides(color = FALSE) +
    theme_minimal()

  p1 <- base + stat_ecdf(aes(l1_norm))
  p2 <- base + stat_ecdf(aes(l2_norm))
  p3 <- base + stat_ecdf(aes(non_zero))
  p4 <- ggplot(weights, aes(weight, color = method)) +
    stat_ecdf(aes(weight)) +
    color_s +
    theme_minimal() +
    theme(legend.position = "top")

  plt <- (p1 | p2 | p3) / p4
  plt + plot_annotation(
    title = tissue,
    subtitle = "ECDFs of weight vector statistics by gene (top) and all weights (bottom)"
  )
}
```


```{r, fig.fullwidth = TRUE, fig.width=10, fig.height=7}
plot_tissue_summary("Liver")
```

```{r, fig.fullwidth = TRUE, fig.width=10, fig.height=7}
plot_tissue_summary("Muscle_Skeletal")
```

```{r, fig.fullwidth = TRUE, fig.width=10, fig.height=7}
plot_tissue_summary("Kidney_Cortex")
```

```{r, fig.fullwidth = TRUE, fig.width=10, fig.height=7}
plot_tissue_summary("Pancreas")
```

## Element-wise comparison of weight vectors

```{r, message=F}
load_summary <- function(tissue) {
  fs::path("..", "results", paste0("weights_summary_", tissue, ".csv")) %>%
    read_csv()
}

plot_diff_summary <- function(tissue_diff_summary, title) {
  tissue_diff_summary %>%
    ggplot(aes(diff_l2, color = paste(method1, method2, sep = " - "))) +
    stat_ecdf() +
    theme_minimal() +
    theme(
      legend.position = "top",
      legend.title = element_blank(),
      plot.title.position = "plot"
    ) +
    labs(x = "|| w1 - w2 ||_2", y = "F(x)") +
    scale_x_continuous(limits = c(0, 2))
}

plot_comparison <- function(t1, t2, t3, t4) {
  p1 <- load_summary(t1) %>% plot_diff_summary() + ggtitle(t1)
  p2 <- load_summary(t2) %>% plot_diff_summary() + ggtitle(t2)
  p3 <- load_summary(t1) %>% plot_diff_summary() + ggtitle(t3)
  p4 <- load_summary(t2) %>% plot_diff_summary() + ggtitle(t4)
  plt <- (p1 + p2) / (p3 + p4)
  plt + plot_annotation(
    title = "Element wise comparison of weight vectors across all genes"
  )
}
```


```{r, message=FALSE, warning=FALSE, fig.fullwidth = TRUE, fig.width=10, fig.height=10}
plot_comparison("Liver", "Muscle_Skeletal", "Kidney_Cortex", "Pancreas")
```

```{r, message=FALSE,  fig.fullwidth = TRUE, fig.width=10, fig.height=10}
load_summary("Liver") %>%
  pivot_wider(
    names_from = c(method1, method2),
    names_sep = "-",
    values_from = diff_l2
  ) %>%
  drop_na() %>%
  select(-gene, -tissue) %>%
  ggpairs()
```

```{r, message=FALSE,  fig.fullwidth = TRUE, fig.width=10, fig.height=10}
load_summary("Muscle_Skeletal") %>%
  pivot_wider(
    names_from = c(method1, method2),
    names_sep = "-",
    values_from = diff_l2
  ) %>%
  drop_na() %>%
  select(-gene, -tissue) %>%
  ggpairs() +
  ggtitle("Muscle Skeletal")
```
